FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install -g npm@11.6.0
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]